/* GENERATED by scripts/build-assets.mjs — do not edit.
   Re-run with `npm run assets`. Sources are in images/, which is gitignored. */

export interface ProductTile { src: string; alt: string }

export const HERO = '/assets/mp/hero.webp'
export const CAROUSEL: readonly string[] = [
  "/assets/mp/carousel-01.webp",
  "/assets/mp/carousel-02.webp",
  "/assets/mp/carousel-03.webp",
  "/assets/mp/carousel-04.webp",
  "/assets/mp/carousel-05.webp"
]
export const BANNERS: readonly string[] = [
  "/assets/mp/banner-01.webp",
  "/assets/mp/banner-02.webp",
  "/assets/mp/banner-03.webp",
  "/assets/mp/banner-04.webp",
  "/assets/mp/banner-05.webp",
  "/assets/mp/banner-06.webp",
  "/assets/mp/banner-07.webp",
  "/assets/mp/banner-08.webp",
  "/assets/mp/banner-09.webp",
  "/assets/mp/banner-10.webp",
  "/assets/mp/banner-11.webp",
  "/assets/mp/banner-12.webp"
]
export const DEVICE_THUMBS: readonly string[] = [
  "/assets/mp/device-01.webp",
  "/assets/mp/device-02.webp",
  "/assets/mp/device-03.webp",
  "/assets/mp/device-04.webp",
  "/assets/mp/device-05.webp",
  "/assets/mp/device-06.webp",
  "/assets/mp/device-07.webp",
  "/assets/mp/device-08.webp",
  "/assets/mp/device-09.webp",
  "/assets/mp/device-10.webp",
  "/assets/mp/device-11.webp",
  "/assets/mp/device-12.webp",
  "/assets/mp/device-13.webp",
  "/assets/mp/device-14.webp",
  "/assets/mp/device-15.webp",
  "/assets/mp/device-16.webp",
  "/assets/mp/device-17.webp",
  "/assets/mp/device-18.webp",
  "/assets/mp/device-19.webp",
  "/assets/mp/device-20.webp",
  "/assets/mp/device-21.webp",
  "/assets/mp/device-22.webp",
  "/assets/mp/device-23.webp",
  "/assets/mp/device-24.webp",
  "/assets/mp/device-25.webp",
  "/assets/mp/device-26.webp",
  "/assets/mp/device-27.webp",
  "/assets/mp/device-28.webp",
  "/assets/mp/device-29.webp",
  "/assets/mp/device-30.webp",
  "/assets/mp/device-31.webp",
  "/assets/mp/device-32.webp",
  "/assets/mp/device-33.webp",
  "/assets/mp/device-34.webp",
  "/assets/mp/device-35.webp",
  "/assets/mp/device-36.webp",
  "/assets/mp/device-37.webp",
  "/assets/mp/device-38.webp",
  "/assets/mp/device-39.webp",
  "/assets/mp/device-40.webp",
  "/assets/mp/device-41.webp",
  "/assets/mp/device-42.webp"
]
export const RETAIL_PRODUCTS: readonly ProductTile[] = [
  {
    "src": "/assets/mp/device-01.webp",
    "alt": "Smartphone"
  },
  {
    "src": "/assets/mp/device-02.webp",
    "alt": "Laptop"
  },
  {
    "src": "/assets/mp/device-03.webp",
    "alt": "Smart watch"
  },
  {
    "src": "/assets/mp/device-04.webp",
    "alt": "Wireless earbuds"
  },
  {
    "src": "/assets/mp/device-05.webp",
    "alt": "Over-ear headphones"
  },
  {
    "src": "/assets/mp/device-06.webp",
    "alt": "Games controller"
  },
  {
    "src": "/assets/mp/device-07.webp",
    "alt": "Smart television"
  },
  {
    "src": "/assets/mp/device-08.webp",
    "alt": "Smart speaker"
  },
  {
    "src": "/assets/mp/device-09.webp",
    "alt": "Voice assistant"
  },
  {
    "src": "/assets/mp/device-10.webp",
    "alt": "Portable speaker"
  },
  {
    "src": "/assets/mp/device-11.webp",
    "alt": "Mirrorless camera"
  },
  {
    "src": "/assets/mp/device-12.webp",
    "alt": "Camera drone"
  }
]
export const ENTERPRISE_PRODUCTS: readonly ProductTile[] = [
  {
    "src": "/assets/mp/product-01.webp",
    "alt": "IoT gateway for connecting field devices"
  },
  {
    "src": "/assets/mp/product-02.webp",
    "alt": "LoRa gateway for long-range sensor networks"
  },
  {
    "src": "/assets/mp/product-03.webp",
    "alt": "Bluetooth low-energy beacon"
  },
  {
    "src": "/assets/mp/product-04.webp",
    "alt": "Compact GPS asset tracker"
  },
  {
    "src": "/assets/mp/product-05.webp",
    "alt": "PIR motion sensor"
  },
  {
    "src": "/assets/mp/product-06.webp",
    "alt": "Compact thermal sensor"
  },
  {
    "src": "/assets/mp/product-07.webp",
    "alt": "Pan-tilt-zoom security camera"
  },
  {
    "src": "/assets/mp/product-08.webp",
    "alt": "Managed network switch"
  },
  {
    "src": "/assets/mp/product-09.webp",
    "alt": "Full-size server rack"
  },
  {
    "src": "/assets/mp/product-10.webp",
    "alt": "EV charging point"
  },
  {
    "src": "/assets/mp/product-11.webp",
    "alt": "Point-of-sale terminal"
  },
  {
    "src": "/assets/mp/product-12.webp",
    "alt": "NFC contactless payment reader"
  }
]
