import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--no-proxy-server'] })
const p = await b.newPage({ viewport:{width:1280,height:1000} })
await p.goto('http://127.0.0.1:4180/', { waitUntil:'networkidle' }); await p.waitForTimeout(1500)
await p.getByRole('button', { name:/demo sign-?in/i }).first().click(); await p.waitForTimeout(1400)
await p.getByRole('button', { name:/Consumer/i }).first().click(); await p.waitForTimeout(1400)
await p.getByRole('button', { name:/Bengaluru, India/i }).first().click(); await p.waitForTimeout(1400)
await p.getByRole('button', { name:/^Sign In$/i }).last().click(); await p.waitForTimeout(6000)
const av = p.getByRole('button', { name:/^PR$/ })
console.log('avatar count', await av.count())
if (await av.count()) { await av.first().click(); await p.waitForTimeout(1800) }
await p.screenshot({ path:'/tmp/menu.png' })
const txt = await p.locator('button, a').allInnerTexts()
console.log(JSON.stringify(txt.filter(t=>t.trim()&&t.length<40)))
await b.close()
