/* Reads the prototype's KB data and emits the migration.
   The prose is copied, never retyped. Re-run to regenerate. */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'mp_data.js');
const OUT = path.join(__dirname, '..', 'supabase', 'migrations', '20260729120000_knowledge_base.sql');

const lines = fs.readFileSync(SRC, 'utf8').split('\n');

/* Grab a top-level `const NAME = ...;` block by brace/bracket balance. */
function grab(name) {
  const start = lines.findIndex(l => l.startsWith('const ' + name));
  if (start < 0) throw new Error('not found: ' + name);
  let depth = 0, started = false, out = [];
  for (let i = start; i < lines.length; i++) {
    out.push(lines[i]);
    for (const ch of lines[i]) {
      if (ch === '{' || ch === '[') { depth++; started = true; }
      if (ch === '}' || ch === ']') depth--;
    }
    if (started && depth <= 0) break;
  }
  const text = out.join('\n').replace(/^const\s+\w+\s*=\s*/, '').replace(/;\s*$/, '');
  return new Function('return ' + text)();   // pure data literals only
}

const ARTICLES = grab('KB_ARTICLES');
const TOURS = grab('KB_TOURS');

/* Prototype view id -> React view id. null means the screen does not exist here. */
const PROTO_VIEW_MAP = {
  consumer: {
    home: 'home', orders: 'orders', billing: 'account', account: 'account',
    plans: 'category', browse: 'category', delivery: 'orders', refunds: 'orders',
    subs: 'subscriptions', auth: 'account',
  },
  partner: {
    home: 'pt-dashboard', listings: 'pt-listings', newlisting: 'pt-newlisting',
    orders: 'pt-orders', settlement: 'pt-settlement', plan: 'pt-plan',
    onboarding: 'pt-onboarding', integrations: 'pt-integrations', audit: 'pt-audit',
    inventory: null, branding: null, collections: null, notes: null, refunds: null,
  },
  operator: {
    home: 'op-dashboard', onboardq: 'op-onboarding', catalogue: 'op-catalogue',
    settlements: 'op-settlement', settlement: 'op-settlement', inventory: 'op-inventory',
    promotions: 'op-promotions', roles: 'op-roles', audit: 'op-audit',
    collections: 'op-dunning',
    rules: null, plans: null, numbers: null, bulk: null, delivery: null,
  },
  buyer: {
    home: 'en-dashboard', approvals: 'en-approvals', browse: 'en-browse',
    orders: 'en-orders', audit: 'en-audit', account: 'en-profile', billing: 'en-profile',
    contracts: null, bulk: null, auth: null,
  },
};

/* The prototype calls the enterprise buyer `buyer`; this app says `enterprise`. */
const PERSONA = { consumer: 'consumer', partner: 'partner', operator: 'operator', buyer: 'enterprise' };

const q = v => v === null || v === undefined ? 'NULL' : "'" + String(v).replace(/'/g, "''") + "'";
const arr = a => !a || !a.length ? "'{}'" : "'{" + a.map(s => '"' + String(s).replace(/"/g, '\\"') + '"').join(',') + "}'";
const json = o => "'" + JSON.stringify(o).replace(/'/g, "''") + "'::jsonb";

const rows = [], tourRows = [];
let published = 0, held = 0;
const heldList = [];

Object.keys(ARTICLES).forEach(protoKey => {
  const persona = PERSONA[protoKey];
  if (!persona) throw new Error('unmapped persona key: ' + protoKey);
  ARTICLES[protoKey].forEach((a, i) => {
    const map = PROTO_VIEW_MAP[protoKey] || {};
    if (a.view && !(a.view in map)) throw new Error(`no mapping for ${protoKey}:${a.view} (article ${a.id})`);
    const view = a.view ? map[a.view] : null;
    const status = view ? 'published' : 'held';
    if (status === 'published') published++; else { held++; heldList.push(`${a.id} (${protoKey}:${a.view || 'no view'})`); }
    rows.push('(' + [
      q(a.id), q(persona), q(a.kind), q(a.title), a.mins || 0, q(a.updated),
      q(view), arr(a.roles), arr(a.tags), q(a.summary), json(a.body || []),
      q(status), i,
    ].join(', ') + ')');
  });
});

Object.keys(TOURS).forEach(protoKey => {
  const persona = PERSONA[protoKey];
  TOURS[protoKey].forEach((t, i) => {
    const map = PROTO_VIEW_MAP[protoKey] || {};
    const stops = (t.stops || []).map(s => ({ view: s.view ? map[s.view] || null : null, at: s.at, say: s.say }));
    tourRows.push('(' + [
      q(t.id), q(persona), q(t.title), t.mins || 0, q(t.why || ''), json(stops), q('held'), i,
    ].join(', ') + ')');
  });
});

const sql = `-- Knowledge base: the prototype's help centre, ported.
--
-- GENERATED by _src/extract-kb.cjs from _src/mp_data.js. Do not hand-edit;
-- re-run the extractor instead. The prose is copied verbatim.
--
-- ${published} articles published, ${held} held.
-- Held articles describe screens this app does not have yet. Their prose is
-- kept so switching one on later is a one-row update:
${heldList.map(h => '--   ' + h).join('\n')}

CREATE TABLE IF NOT EXISTS kb_articles (
  id text PRIMARY KEY,
  persona text NOT NULL,
  kind text NOT NULL,
  title text NOT NULL,
  mins int NOT NULL DEFAULT 0,
  updated text,
  view text,
  roles text[] NOT NULL DEFAULT '{}',
  tags text[] NOT NULL DEFAULT '{}',
  summary text NOT NULL DEFAULT '',
  body jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'published',
  sort_order int NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_kb_articles_persona ON kb_articles(persona, status);

CREATE TABLE IF NOT EXISTS kb_tours (
  id text PRIMARY KEY,
  persona text NOT NULL,
  title text NOT NULL,
  mins int NOT NULL DEFAULT 0,
  why text NOT NULL DEFAULT '',
  stops jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'held',
  sort_order int NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_kb_tours_persona ON kb_tours(persona, status);

ALTER TABLE kb_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb_tours    ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['kb_articles','kb_tours'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "anon_all_%1$s" ON %1$I', t);
    EXECUTE format('CREATE POLICY "anon_all_%1$s" ON %1$I FOR ALL TO anon, authenticated USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

INSERT INTO kb_articles (id, persona, kind, title, mins, updated, view, roles, tags, summary, body, status, sort_order) VALUES
${rows.join(',\n')}
ON CONFLICT (id) DO NOTHING;

INSERT INTO kb_tours (id, persona, title, mins, why, stops, status, sort_order) VALUES
${tourRows.join(',\n')}
ON CONFLICT (id) DO NOTHING;
`;

fs.writeFileSync(OUT, sql, 'utf8');
console.log(`wrote ${OUT}`);
console.log(`articles: ${published} published, ${held} held (total ${published + held})`);
console.log(`tours: ${tourRows.length} (all held until Phase 2)`);
