/* Ninety-six articles about a user interface, with two pictures between them.
 *
 * The block model has carried `image` and `video` since media blocks landed —
 * a typed union, an embed-host allowlist, `kb_embeddable` in the database and
 * `embeddable` beside it, a renderer shared by the full knowledge base and the
 * contextual help panel. All of it built, and one article on file using an
 * image and one using a video. A capability nothing exercises is the same kind
 * of claim as a sort order nothing writes.
 *
 * Worse than the absence was the presence. The one article that did carry a
 * picture carried a stock photograph from a photo library, with alt text
 * reading "The settlement runs screen, with the period list on the left and the
 * Approve button at the end of each row." It is not that screen. A reader who
 * cannot see the image is told there is a button in a place, and a reader who
 * can see it is shown somebody else's desk. That is worse than no picture at
 * all, and it is removed here rather than joined by eighty more like it.
 *
 * The pictures are of the screens themselves: every screen in all four
 * consoles, captured through the ordinary sign-in as the persona that reads the
 * article, and served from the `kb-assets` bucket this marketplace already
 * owns. Eighty-two screens, eighty-four articles — two screens carry two
 * articles each, which is why the counts differ.
 *
 * The videos are placeholders and say so in their own captions. What is real
 * about them is the plumbing: they are rotated across all four URL forms the
 * allowlist accepts — a Vimeo player URL, a Vimeo watch page, a YouTube watch
 * page and a youtu.be short link — because `embedUrl` has a conversion branch
 * for each and until now no article on file exercised any of them. A recorded
 * walkthrough replaces the URL in place and nothing else has to change.
 *
 * A walkthrough goes on the articles that walk you through doing something —
 * `howto`, `start` and `fix`. A `concept` or a `policy` article has nothing to
 * watch, and a video on one is a play button that wastes the reader's time.
 *
 * Rebuilt rather than appended to, so running this twice produces what running
 * it once did: the prose is kept in its order, the picture goes second where
 * a reader is oriented by it, and the walkthrough goes last.
 */

create temporary table kb_media (id text primary key, img jsonb, vid jsonb) on commit drop;

insert into kb_media (id, img, vid) values
  ('KB-C04', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/account.jpg','alt','The My details screen in the storefront, as it appears when you open it.','caption','My details — the storefront.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: A payment failed. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-C06', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/account.jpg','alt','The My details screen in the storefront, as it appears when you open it.','caption','My details — the storefront.'), null),
  ('KB-C02', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/category.jpg','alt','A category page in the storefront, as it appears when you open it.','caption','A category page in the storefront.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Compare before you buy. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-C08', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/checkout.jpg','alt','The Checkout screen in the storefront, as it appears when you open it.','caption','Checkout — the storefront.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Checking out, and what you are charged. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-C01', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/home.jpg','alt','The storefront home page in the storefront, as it appears when you open it.','caption','The storefront home page in the storefront.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Getting started. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-C10', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/kb.jpg','alt','The Help & Support screen in the storefront, as it appears when you open it.','caption','Help & Support — the storefront.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Finding an answer here. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-C05', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/orders.jpg','alt','The My Orders screen in the storefront, as it appears when you open it.','caption','My Orders — the storefront.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Write a review. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-C07', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/product.jpg','alt','A product page in the storefront, as it appears when you open it.','caption','A product page in the storefront.'), null),
  ('KB-C09', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/rewards.jpg','alt','The Rewards screen in the storefront, as it appears when you open it.','caption','Rewards — the storefront.'), null),
  ('KB-C03', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/subscriptions.jpg','alt','The Subscriptions screen in the storefront, as it appears when you open it.','caption','Subscriptions — the storefront.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Manage a subscription. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B22', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-agreement.jpg','alt','The Your Agreement screen in the business account, as it appears when you open it.','caption','Your Agreement — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Your agreement with Aventa. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B02', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-approvals.jpg','alt','The Approvals screen in the business account, as it appears when you open it.','caption','Approvals — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Raise and track a requisition. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B19', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-audit.jpg','alt','The Audit Log screen in the business account, as it appears when you open it.','caption','Audit Log — the business account.'), null),
  ('KB-B13', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-billing.jpg','alt','The Billing screen in the business account, as it appears when you open it.','caption','Billing — the business account.'), null),
  ('KB-B07', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-browse.jpg','alt','The Browse Catalogue screen in the business account, as it appears when you open it.','caption','Browse Catalogue — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Buying from the business catalogue. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B01', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-dashboard.jpg','alt','The Dashboard screen in the business account, as it appears when you open it.','caption','Dashboard — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: How buying here works. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B10', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-devices.jpg','alt','The Devices screen in the business account, as it appears when you open it.','caption','Devices — the business account.'), null),
  ('KB-B08', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-iot.jpg','alt','The IoT screen in the business account, as it appears when you open it.','caption','IoT — the business account.'), null),
  ('KB-B20', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-kb.jpg','alt','The Knowledge base screen in the business account, as it appears when you open it.','caption','Knowledge base — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Using the business knowledge base. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B17', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-notifications.jpg','alt','The Notifications screen in the business account, as it appears when you open it.','caption','Notifications — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Notifications for the account. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B21', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-numbers.jpg','alt','The Numbers & SIMs screen in the business account, as it appears when you open it.','caption','Numbers & SIMs — the business account.'), null),
  ('KB-B06', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-orders.jpg','alt','The Orders screen in the business account, as it appears when you open it.','caption','Orders — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Something has not arrived. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B05', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-profile.jpg','alt','The My Details screen in the business account, as it appears when you open it.','caption','My Details — the business account.'), null),
  ('KB-B12', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-refunds.jpg','alt','The Refunds screen in the business account, as it appears when you open it.','caption','Refunds — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Refunds on the account. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B15', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-rewards.jpg','alt','The Rewards screen in the business account, as it appears when you open it.','caption','Rewards — the business account.'), null),
  ('KB-B09', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-security.jpg','alt','The Security screen in the business account, as it appears when you open it.','caption','Security — the business account.'), null),
  ('KB-B11', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-subs.jpg','alt','The Subscriptions screen in the business account, as it appears when you open it.','caption','Subscriptions — the business account.'), null),
  ('KB-B16', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-support.jpg','alt','The Support screen in the business account, as it appears when you open it.','caption','Support — the business account.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Getting support. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-B18', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-team.jpg','alt','The Team & Roles screen in the business account, as it appears when you open it.','caption','Team & Roles — the business account.'), null),
  ('KB-B14', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/en-wallet.jpg','alt','The Wallet screen in the business account, as it appears when you open it.','caption','Wallet — the business account.'), null),
  ('KB-O09', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-audit.jpg','alt','The Audit Trail screen in the marketplace operator console, as it appears when you open it.','caption','Audit Trail — the marketplace operator console.'), null),
  ('KB-O17', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-banners.jpg','alt','The Storefront Banners screen in the marketplace operator console, as it appears when you open it.','caption','Storefront Banners — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Storefront banners. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O28', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-billtemplates.jpg','alt','The Bill Templates screen in the marketplace operator console, as it appears when you open it.','caption','Bill Templates — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Bill and invoice templates. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O03', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-catalogue.jpg','alt','The Catalogue Review screen in the marketplace operator console, as it appears when you open it.','caption','Catalogue Review — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Review a listing and decide it. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O18', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-channels.jpg','alt','The Channels screen in the marketplace operator console, as it appears when you open it.','caption','Channels — the marketplace operator console.'), null),
  ('KB-O38', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-contracts.jpg','alt','The Agreements screen in the marketplace operator console, as it appears when you open it.','caption','Agreements — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: The agreement register. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O37', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-credit.jpg','alt','The Credit & Exposure screen in the marketplace operator console, as it appears when you open it.','caption','Credit & Exposure — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Credit, deposits and what a hold actually does. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O01', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-dashboard.jpg','alt','The Dashboard screen in the marketplace operator console, as it appears when you open it.','caption','Dashboard — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: What this console is for. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O15', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-developer.jpg','alt','The Developer Portal screen in the marketplace operator console, as it appears when you open it.','caption','Developer Portal — the marketplace operator console.'), null),
  ('KB-O36', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-disputes.jpg','alt','The Disputes screen in the marketplace operator console, as it appears when you open it.','caption','Disputes — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Working a dispute. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O14', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-dunning.jpg','alt','The Collections screen in the marketplace operator console, as it appears when you open it.','caption','Collections — the marketplace operator console.'), null),
  ('KB-O22', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-feedback.jpg','alt','The Content Feedback screen in the marketplace operator console, as it appears when you open it.','caption','Content Feedback — the marketplace operator console.'), null),
  ('KB-O12', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-inventory.jpg','alt','The Inventory & WMS screen in the marketplace operator console, as it appears when you open it.','caption','Inventory & WMS — the marketplace operator console.'), null),
  ('KB-O31', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-kb.jpg','alt','The Knowledge base screen in the marketplace operator console, as it appears when you open it.','caption','Knowledge base — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Running the knowledge base. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O26', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-ledger.jpg','alt','The General Ledger screen in the marketplace operator console, as it appears when you open it.','caption','General Ledger — the marketplace operator console.'), null),
  ('KB-O29', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-markets.jpg','alt','The Markets & Currencies screen in the marketplace operator console, as it appears when you open it.','caption','Markets & Currencies — the marketplace operator console.'), null),
  ('KB-O34', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-notes.jpg','alt','The Credit & Debit Notes screen in the marketplace operator console, as it appears when you open it.','caption','Credit & Debit Notes — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Raise a credit or debit note. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O19', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-notifications.jpg','alt','The Notifications screen in the marketplace operator console, as it appears when you open it.','caption','Notifications — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Notification rules and templates. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O32', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-numbers.jpg','alt','The Numbers & SIMs screen in the marketplace operator console, as it appears when you open it.','caption','Numbers & SIMs — the marketplace operator console.'), null),
  ('KB-O02', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-onboarding.jpg','alt','The Partner Onboarding screen in the marketplace operator console, as it appears when you open it.','caption','Partner Onboarding — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Onboard a seller through the seven gates. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O35', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-orders.jpg','alt','The Orders screen in the marketplace operator console, as it appears when you open it.','caption','Orders — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Working somebody else''s order. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O11', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-partners.jpg','alt','The Sellers screen in the marketplace operator console, as it appears when you open it.','caption','Sellers — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: The seller directory. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O30', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-profile.jpg','alt','The My Details screen in the marketplace operator console, as it appears when you open it.','caption','My Details — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Your own details. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O16', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-promotions.jpg','alt','The Promotions screen in the marketplace operator console, as it appears when you open it.','caption','Promotions — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Promotions. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O24', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-refunds.jpg','alt','The Refunds screen in the marketplace operator console, as it appears when you open it.','caption','Refunds — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Refunds. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O21', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-reviews.jpg','alt','The Reviews screen in the marketplace operator console, as it appears when you open it.','caption','Reviews — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Moderating reviews. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O27', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-revshare.jpg','alt','The Revenue Share screen in the marketplace operator console, as it appears when you open it.','caption','Revenue Share — the marketplace operator console.'), null),
  ('KB-O25', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-rewards.jpg','alt','The Rewards screen in the marketplace operator console, as it appears when you open it.','caption','Rewards — the marketplace operator console.'), null),
  ('KB-O20', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-roles.jpg','alt','The Roles & Users screen in the marketplace operator console, as it appears when you open it.','caption','Roles & Users — the marketplace operator console.'), null),
  ('KB-O06', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-settlement.jpg','alt','The Settlement Runs screen in the marketplace operator console, as it appears when you open it.','caption','Settlement Runs — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Approve a settlement run. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O33', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-shelves.jpg','alt','The Shelves & Rules screen in the marketplace operator console, as it appears when you open it.','caption','Shelves & Rules — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Change what a shelf demands. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O13', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-tickets.jpg','alt','The Tickets & SLA screen in the marketplace operator console, as it appears when you open it.','caption','Tickets & SLA — the marketplace operator console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Tickets and the SLA clock. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-O23', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/op-wallets.jpg','alt','The Wallets screen in the marketplace operator console, as it appears when you open it.','caption','Wallets — the marketplace operator console.'), null),
  ('KB-P21', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-audit.jpg','alt','The Audit Log screen in the seller console, as it appears when you open it.','caption','Audit Log — the seller console.'), null),
  ('KB-P01', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-dashboard.jpg','alt','The Dashboard screen in the seller console, as it appears when you open it.','caption','Dashboard — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Selling here: the short version. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P09', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-developer.jpg','alt','The Developer screen in the seller console, as it appears when you open it.','caption','Developer — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Get an API key and make your first call. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P04', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-integrations.jpg','alt','The Integrations screen in the seller console, as it appears when you open it.','caption','Integrations — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Make orders fulfil themselves. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P24', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-kb.jpg','alt','The Knowledge base screen in the seller console, as it appears when you open it.','caption','Knowledge base — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Using the seller knowledge base. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P07', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-listings.jpg','alt','The My Listings screen in the seller console, as it appears when you open it.','caption','My Listings — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: My listing was rejected. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P08', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-listings.jpg','alt','The My Listings screen in the seller console, as it appears when you open it.','caption','My Listings — the seller console.'), null),
  ('KB-P02', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-newlisting.jpg','alt','The New Listing screen in the seller console, as it appears when you open it.','caption','New Listing — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Create a listing that passes review first time. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P19', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-notifications.jpg','alt','The Notifications screen in the seller console, as it appears when you open it.','caption','Notifications — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://youtu.be/aqz-KE-bpKQ','caption','Walkthrough: Your notifications. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P12', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-onboarding.jpg','alt','The Onboarding screen in the seller console, as it appears when you open it.','caption','Onboarding — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Getting through onboarding. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P13', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-orders.jpg','alt','The Orders screen in the seller console, as it appears when you open it.','caption','Orders — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Your orders. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P15', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-performance.jpg','alt','The Performance screen in the seller console, as it appears when you open it.','caption','Performance — the seller console.'), null),
  ('KB-P14', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-plan.jpg','alt','The Settlement Plan screen in the seller console, as it appears when you open it.','caption','Settlement Plan — the seller console.'), null),
  ('KB-P23', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-profile.jpg','alt','The My Details screen in the seller console, as it appears when you open it.','caption','My Details — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://player.vimeo.com/video/76979871','caption','Walkthrough: Your seller details. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P17', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-refunds.jpg','alt','The Refunds screen in the seller console, as it appears when you open it.','caption','Refunds — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Refunds and returns. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P22', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-reviews.jpg','alt','The Reviews screen in the seller console, as it appears when you open it.','caption','Reviews — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://vimeo.com/76979871','caption','Walkthrough: Reviews of your products. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P18', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-rewards.jpg','alt','The Rewards screen in the seller console, as it appears when you open it.','caption','Rewards — the seller console.'), null),
  ('KB-P03', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-settlement.jpg','alt','The Settlement screen in the seller console, as it appears when you open it.','caption','Settlement — the seller console.'), null),
  ('KB-P16', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-support.jpg','alt','The Disputes & Support screen in the seller console, as it appears when you open it.','caption','Disputes & Support — the seller console.'), jsonb_build_object('kind','video','heading','Watch it done','url','https://www.youtube.com/watch?v=aqz-KE-bpKQ','caption','Walkthrough: Getting support. Placeholder footage for now — the recorded version replaces it in place.')),
  ('KB-P20', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-team.jpg','alt','The Your Team screen in the seller console, as it appears when you open it.','caption','Your Team — the seller console.'), null),
  ('KB-P26', jsonb_build_object('kind','image','heading','The screen this is about','src','https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/screens/pt-wholesale.jpg','alt','The Wholesale screen in the seller console, as it appears when you open it.','caption','Wholesale — the seller console.'), null)
;

/* Prose only, worked out first. The article's own words in their own order —
   anything an earlier run of this migration added is dropped and rebuilt, which
   is what makes a second run produce what the first one did.

   In its own table rather than a LATERAL, because `UPDATE ... FROM` cannot
   reach the row being updated from a lateral subquery. */
create temporary table kb_prose on commit drop as
select a.id,
       coalesce((select jsonb_agg(e order by n)
                   from jsonb_array_elements(a.body) with ordinality t(e, n)
                  where e ->> 'kind' = 'prose'), '[]'::jsonb) as blocks
  from public.kb_articles a
 where a.id in (select id from kb_media);

update public.kb_articles a set body =
  jsonb_build_array(p.blocks -> 0, m.img)
  || coalesce((select jsonb_agg(e) from jsonb_array_elements(p.blocks) with ordinality t(e, n)
                where n > 1), '[]'::jsonb)
  || case when m.vid is null then '[]'::jsonb else jsonb_build_array(m.vid) end
from kb_media m
join kb_prose p on p.id = m.id
where a.id = m.id and jsonb_array_length(p.blocks) > 0;

do $$
declare n integer; bad text;
begin
  select count(*) into n from public.kb_articles
   where view is not null and not (body::text like '%"image"%');
  if n > 0 then raise exception '% articles about a screen still have no picture of it.', n; end if;

  /* The photograph is gone, and nothing else points outside this marketplace. */
  select string_agg(a.id, ', ') into bad from public.kb_articles a,
    lateral jsonb_array_elements(a.body) e
   where e ->> 'kind' = 'image'
     and e ->> 'src' not like 'https://playukebhnkrdrcsorhj.supabase.co/storage/v1/object/public/kb-assets/%';
  if bad is not null then
    raise exception 'These articles still illustrate themselves with somebody else''s picture: %', bad;
  end if;

  /* Every picture describes itself. The reader most likely to need the
     description is the one who cannot see it. */
  select string_agg(a.id, ', ') into bad from public.kb_articles a,
    lateral jsonb_array_elements(a.body) e
   where e ->> 'kind' = 'image' and coalesce(trim(e ->> 'alt'), '') = '';
  if bad is not null then raise exception 'Images with no alt text: %', bad; end if;

  /* And every video is on a host this marketplace will frame — the same rule
     `kb_embeddable` holds a save to, checked over what is actually on file. */
  select string_agg(a.id, ', ') into bad from public.kb_articles a,
    lateral jsonb_array_elements(a.body) e
   where e ->> 'kind' = 'video' and not public.kb_embeddable(e ->> 'url');
  if bad is not null then raise exception 'Videos this marketplace will not frame: %', bad; end if;

  select count(distinct e ->> 'url') into n from public.kb_articles a,
    lateral jsonb_array_elements(a.body) e where e ->> 'kind' = 'video';
  if n < 4 then
    raise exception 'Only % video URL forms on file; the conversion branches are not all exercised.', n;
  end if;
end $$;
